export const DISCORD_API_URL = 'https://discord.com/api/v9';

export const SPOTIFY_API_URL = 'https://api.spotify.com/v1';

export const FILTERS = [
    'bassboost_low',
    'bassboost',
    'bassboost_high',
    '8D',
    'vaporwave',
    'nightcore',
    'phaser',
    'tremolo',
    'vibrato',
    'reverse',
    'treble',
    'normalizer',
    'normalizer2',
    'surrounding',
    'pulsator',
    'subboost',
    'karaoke',
    'flanger',
    'gate',
    'haas',
    'mcompand',
    'mono',
    'mstlr',
    'mstrr',
    'compressor',
    'expander',
    'softlimiter',
    'chorus',
    'chorus2d',
    'chorus3d',
    'fadein',
    'dim',
    'earrape',
];
